### ISSUE TITLE
后端日志不显示报错信息

### ISSUE THREAD

**Issue by ZimaBlueee** [vastxie/ChatGPT-Web#4]
![image](https://github.com/vastxie/ChatGPT-Web/assets/53747502/ab8e00c1-8247-43f9-b6bf-adebb3f14d3b)

![image](https://github.com/vastxie/ChatGPT-Web/assets/53747502/61b79f4e-bc08-4958-b632-a137b4b6d8e9)

我使用`pm2 logs chatweb`查看日志，chrome控制台打印500报错，但是后端不显示报错信息，只显示sql日志。

请问怎么配置才能看到具体的500报错信息呢？期待您的回复

**Comment by vastxie** [comment]
pm2 logs chatweb --err

**Comment by ZimaBlueee** [comment]
感谢，已解决
